stages:
  - deploy

deploy_container:
  stage: deploy
  image: docker:20 # Die spezifische Version von Docker verwenden
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build --build-arg ARCH=arm64 -t $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH --platform linux/arm64 -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  only:
    - main
