stages:
  - deploy

deploy_container:
  stage: deploy
  image: docker:23
  services:
    - docker:dind
  variables:
    DOCKER_CLI_EXPERIMENTAL: enabled 
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use --name mybuilder  # Erstelle und aktiviere den Buildx-Builder
    - docker buildx build --platform linux/arm64 -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  only:
    - main
