stages:
  - deploy

deploy_container:
  stage: deploy
  image: docker:latest  # Verwende die neueste Version von Docker oder eine, die buildx unterstützt
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use --name mybuilder  # Erstelle und aktiviere den Buildx-Builder
    - docker buildx build --platform linux/arm64 -t $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH --push .
  only:
    - main
